
spring:
  datasource:
    url: jdbc:mysql://xcape-business-sdk-dev-db.c7jldwntoo2t.ap-northeast-1.rds.amazonaws.com/xcape
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(NFNqmW9gwS4I/HZraWIe09f0AEFCj1s1)
    password: ENC(dDM/mQa7RRtGhNa8av4IGtaEnBhIe+fm)

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
