spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 50MB


# AWS properties
cloud:
  aws:
    credential:
      accessKey: AKIAQO6NIBUKD6AAZ2XN
      secretKey: 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

    s3:
      region: ap-northeast-1
      bucket: xcape-business-sdk-uploads
