spring:
  profiles:
    active: local

#cloud:
#  aws:
#    credential:
#      accessKey: ENC(HxN4BBZgdlFjQm3aYeWsKLTlJX+GYMTH26xzHHnE1gg=)
#      secretKey: ENC(bI6KJx2SEqxsWv5Y8MSRsyJyfGofpNitFfREgv+egCSpU02+dBT8xIsErK0VqjdpXruZmRDuOcI=)
#
#    s3:
#      region: ap-northeast-2
#      bucket: xcape-business-sdk-uploads

---
spring:
  datasource:
    url: jdbc:mysql://xcape-business-sdk-dev-db.c7jldwntoo2t.ap-northeast-1.rds.amazonaws.com/xcape
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(NFNqmW9gwS4I/HZraWIe09f0AEFCj1s1)
    password: ENC(dDM/mQa7RRtGhNa8av4IGtaEnBhIe+fm)

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 50MB
  config:
    activate:
      on-profile: local

  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: scheduling-

kakao:
  host: https://api-alimtalk.cloud.toast.com
  senderKey: ENC(Uz5eKsiJjt+Ci68GruukDvUo//FjviaxmBBJsdgolLMZsWhKyWpZI4SSxctEaKnbz/TmB59Z9RA=)
  secretKey: ENC(vrsnnwSRWVVq0mDqmdakvv1vKmFGmzIA)
  appKey: ENC(uTaPfgQJ/uoDlagTSbWSGfGRmcZ+teA6Ap7hQaCXaxg=)
  templateCode:
    authenticate: xcape-authenticate

sms:
  sendNo: 01093736081
  host: https://api-sms.cloud.toast.com
  secretKey: ENC(erqLmX533rM+812LB2NPAoHQQ3Z5BWu3)
  appKey: ENC(dukcgC1Gns2PGtnOvgx/7XVgVUz4pTLL+1a99ZxeL2E=)

server:
  port: 8900

---
spring:
  datasource:
    url: jdbc:mysql://xcape-business-sdk-dev-db.c7jldwntoo2t.ap-northeast-1.rds.amazonaws.com/xcape
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(NFNqmW9gwS4I/HZraWIe09f0AEFCj1s1)
    password: ENC(dDM/mQa7RRtGhNa8av4IGtaEnBhIe+fm)
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 50MB

kakao:
  host: https://api-alimtalk.cloud.toast.com
  senderKey: ENC(Uz5eKsiJjt+Ci68GruukDvUo//FjviaxmBBJsdgolLMZsWhKyWpZI4SSxctEaKnbz/TmB59Z9RA=)
  secretKey: ENC(vrsnnwSRWVVq0mDqmdakvv1vKmFGmzIA)
  appKey: ENC(uTaPfgQJ/uoDlagTSbWSGfGRmcZ+teA6Ap7hQaCXaxg=)
  templateCode:
    authenticate: xcape-authenticate

sms:
  sendNo: 01093736081
  host: https://api-sms.cloud.toast.com
  secretKey: ENC(erqLmX533rM+812LB2NPAoHQQ3Z5BWu3)
  appKey: ENC(dukcgC1Gns2PGtnOvgx/7XVgVUz4pTLL+1a99ZxeL2E=)

server:
  port: 5000
