spring:
  profiles:
    active: local

cloud:
  aws:
    credential:
      accessKey: AKIAQO6NIBUKD6AAZ2XN
      secretKey: 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

    s3:
      region: ap-northeast-2
      bucket: xcape-business-sdk-uploads

---
spring:
  datasource:
    url: jdbc:mysql://xcape-business-sdk-dev-db.c7jldwntoo2t.ap-northeast-1.rds.amazonaws.com/xcape
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chameleondev
    password: leekoseo9494*

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 50MB
  config:
    activate:
      on-profile: local

server:
  port: 8900

---
spring:
  datasource:
    url: jdbc:mysql://xcape-business-sdk-dev-db.c7jldwntoo2t.ap-northeast-1.rds.amazonaws.com/xcape
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chameleondev
    password: leekoseo9494*
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 50MB

server:
  port: 5000
